# TravisCI config for sommersoft/aws_s3_testing

dist: xenial
language: python
python: "3.6"

addons:
  artifacts:
    paths:
    - $(ls $TRAVIS_BUILD_DIR/web/* | tr "\n" ":")
    target_paths: /adabot
    debug: true

script:
  - mkdir -p web
  - cd adabot
  - python -u -m subfolder.script $TRAVIS_BUILD_DIR/web/libraries.json
