# TravisCI config for sommersoft/aws_s3_testing

dist: xenial
language: python
python: "3.6"

addons:
  artifacts:
    paths:
    - $(ls web/* | tr "\n" ":")
    target_paths: /adabot
    debug: true

script:
  - mkdir -p web
  - cd subfolder
  - python -u -m script $TRAVIS_BUILD_DIR/web/test_file.txt
  - cd ..
